M48
; DRILL file {KiCad 9.0.5} date 2025-11-09T16:33:00+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-11-09T16:33:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X223.2Y-114.1
X223.2Y-118.5
T2
X190.0Y-100.0
X190.0Y-130.0
X225.0Y-100.0
X225.0Y-130.0
M30
